services:
  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379
    container_name: redis

  forum-backend:
    image: blackfox89/myrepository:forum-backend
    build:
      context: .
      dockerfile: Dockerfile_development
      args:
        - MVN_PROFILE=sviluppo
    container_name: forum-backend
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ${PATH_SECRETS}.env-sviluppo
    restart: unless-stopped
    depends_on:
      - redis