version: "3"
services:
	redis:
		image: redis:alpine3.18
        container_name: redis
        
	forum-backend:
        image: blackfox89/myrepository:forum-backend
        build: 
            context: forum-backend
            dockerfile: Dockerfile_development
        container_name: forum-backend    
		ports:
			- 8083:8083
        extra_hosts:
            - "host.docker.internal:host-gateway"
		depends_on:
			- redis
        environment:
           spring.datasource.username: postgres
           spring.datasource.password: /run/secrets/db_password
           spring.mail.username: test@test.com
           spring.mail.password: /run/secrets/mail_password
           spring.redis.host: localhost
           spring.redis.password: /run/secrets/redis_password
        secrets:
           - db_password
           - mail_password
           - redis_password
        restart: unless-stopped
            
secrets:
   db_password:
     file: /home/francesco/secrets/db_password.txt
   mail_password:
     file: /home/francesco/secrets/mail_password.txt
   mail_password:
     file: /home/francesco/secrets/redis_password.txt
